/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yvvnpnzuoqatahnfnrcj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dm5wbnp1b3FhdGFobmZucmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5NDMxOTAsImV4cCI6MjEwMTUxOTE5MH0.JkUC00JEW-7XCPVsmOK-oO-d9rktj-vuQ6kQupkiMc4"